openapi: '3.0.3'
info:
  description: Distributed Key Value Store
  version: 1.0.0
  title: Distributed Key Value Store
paths:
  /ask:
    put:
      description: Updates view
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                view:
                  type: array
                  items:
                    type: object
                    properties:
                      address:
                        type: string
                      id:
                        type: number
                    required:
                      - address
                      - id
                    additionalProperties: false
              required:
                - view
              additionalProperties: false
      responses:
        200:
          description: View updated 
